name: Publish Artifacts and Commit Push

on:
  push:

jobs:
  create-files:
    runs-on: ubuntu-latest
    steps:
      - name: Create file 1
        run: echo "File 1 content" > file1.txt
      - name: Upload file 1
        uses: actions/upload-artifact@v2
        with:
          name: my-artifact
          path: file1.txt

      - name: Create file 2
        run: echo "File 2 content" > file2.txt
      - name: Upload file 2
        uses: actions/upload-artifact@v2
        with:
          name: my-artifact
          path: file2.txt

  download-and-commit:
    runs-on: ubuntu-latest
    needs: create-files
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: my-artifact

      - name: Combine files
        run: |
          cat file1.txt file2.txt > combined.txt

      - name: Commit and push
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git add .
          git commit -m "Combined files"
          git push
