name: Publish Artifacts and Commit Push

on:
  push:

jobs:
  create-files:
    runs-on: ubuntu-latest
    steps:
      - name: Create file 1
        run: echo "File 1 content" > file1.txt
      - name: Upload file 1
        uses: actions/upload-artifact@v4
        with:
          name: metrics
          path: file1.txt

      - name: Create file 2
        run: echo "File 2 content" > file2.txt
      - name: Upload file 2
        uses: actions/upload-artifact@v4
        with:
          name: metrics
          path: file2.txt

  download-and-commit:
    runs-on: ubuntu-latest
    needs: create-files
    steps:
      - name: Checkout dennykorsukewitz
        uses: actions/checkout@v4
        env:
          fetch-depth: "1"
      - name: Git Pull
        run: git pull
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: metrics
      - name: Add and Commit
        uses: EndBug/add-and-commit@v9
        with:
          message: "Updated Metrics: Data."
