---
name: Badges

on:
  # Runs on pushes targeting the default branch
  push:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


jobs:
  # Build job
  Build:
    runs-on: ubuntu-22.04 # ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        env:
          fetch-depth: "1"
        with:
          path: repository

      - name: Create Snippet Counter Badge
        uses: schneegans/dynamic-badges-action@v1.6.0
        with:
          auth: ${{ secrets.GIST }}
          gistID: 620f530386aae95ce25703b8644d16af
          filename: DK4Znuny-VisualStudioCode:snippets.json
          label: Snippets
          message: 1410
          color: blue
