---
name: Lint
on:
  push:
  pull_request:

jobs:
  Lint:
    name: Lint Code Base
    runs-on: ubuntu-22.04 # ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          path: package

      - name: Check out DK4
        uses: actions/checkout@v3
        env:
          fetch-depth: "1"
        with:
          repository: dennykorsukewitz/DK4
          path: DK4

      - name: Branch Name
        run: echo running on branch "${GITHUB_REF##*/}"

      - name: Lint Code Base
        uses: github/super-linter@v4
        env:
          DEFAULT_BRANCH: ${GITHUB_REF##*/}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LINTER_RULES_PATH: 'DK4/.github/linters'
          VALIDATE_ALL_CODEBASE: true
          VALIDATE_JSCPD: false