name: GitHub Pages
on:
  push:
    branches:
      - NEVER
      - main
      - dev
      - dev-update
    paths-ignore:
      - .gitignore
      - README.md
      - LICENSE

  workflow_dispatch: # Allows you to run this workflow manually from the Actions tab

permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  Build:
    runs-on: ubuntu-22.04 # ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v3
        env:
          fetch-depth: "1"
        with:
          path: repository
          # submodules: true
          # If using the 'assets' git submodule from Chirpy Starter, uncomment above
          # (See: https://github.com/cotes2020/chirpy-starter/tree/main/assets)

      - name: Upload site artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: "repository/${{ steps.pages.outputs.base_path }}"

  Deploy:
    environment:
      name: GitHub-Pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
