name: GitHub Pages
on:
  push:
    branches:
      - main
      - dev
      - dev-update
    # paths-ignore:
    #   - .gitignore
    #   - README.md
    #   - LICENSE

  workflow_dispatch: # Allows you to run this workflow manually from the Actions tab

jobs:
  Screenshot:
    name: Screenshot
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - name: Screenshot Website
      uses: swinton/screenshot-website@v1.x
      with:
        source: https://karldaeubel.github.io/PenAndPaperFloorplanner/
        destination: images/screenshot-${{ matrix.os }}.png
        full-page: true